-- join 
-- emp(deptno) , dept(deptno) 한테이블처럼 사용하는 방법
-- (0) SQL-99이전방식(비표준)
SELECT  EMPNO, ENAME, D.DEPTNO, DNAME  --겹치는 친구만 소속을 밝혀도 됨.
FROM    EMP E, DEPT D
WHERE   E.DEPTNO = D.DEPTNO;

--SQL-99(표준)
-- (1) join on
SELECT  EMPNO, ENAME, D.DEPTNO, DNAME 
FROM    EMP E JOIN DEPT D ON( E.DEPTNO = D.DEPTNO);

--SQL-99(표준)
-- (2) join using  --공통사항은 빼고 입력.
SELECT  EMPNO, ENAME, DEPTNO, DNAME 
FROM    EMP E JOIN DEPT D USING( DEPTNO);

--SQL-99(표준)
-- (3) natural join
SELECT  EMPNO, ENAME, DEPTNO, DNAME 
FROM    EMP E NATURAL JOIN DEPT D ;

-- (4) (+) NULL로 보충   SQL-99이전방식(비표준)
select  * from dept;

SELECT  EMPNO, ENAME, D.DEPTNO, DNAME  
FROM    EMP E, DEPT D
WHERE   E.DEPTNO(+) = D.DEPTNO;

-- (5) RIGHT OUTER JOIN 
SELECT  EMPNO, ENAME, D.DEPTNO, DNAME  
FROM    EMP E RIGHT OUTER JOIN DEPT D ON(E.DEPTNO = D.DEPTNO);

-- (6) LEFT OUTER JOIN 
SELECT  EMPNO, ENAME, D.DEPTNO, DNAME  
FROM    DEPT D LEFT OUTER JOIN EMP E ON(E.DEPTNO = D.DEPTNO);

-- (7) FULL OUTER JOIN 
SELECT  EMPNO, ENAME, D.DEPTNO, DNAME  
FROM    DEPT D FULL OUTER JOIN EMP E ON(E.DEPTNO = D.DEPTNO);










